---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/yaca/cdc-bintan.yacanet.com/
    - /bin/rm -rf $DEPLOYPATH/static
    - /bin/rm -rf $DEPLOYPATH/*.js
    - /bin/cp -R build/* $DEPLOYPATH
    - /bin/cp public/.htaccess $DEPLOYPATH
 
