---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/yaca/cdc-bintan.yacanet.com/
    - /bin/rm -rf $DEPLOYPATH/static
    - /bin/cp -R build/* $DEPLOYPATH
    - /usr/bin/git push origin master -u
